const gnomes = [
  {
    name: "Buff Gnome",
    rizz: 10,
    magic: 2,
    strength: 9,
    looks: 10,
    image: "images/buffgnome.jpg",
  },
  {
    name: "Scandalous Gnome",
    rizz: 6,
    magic: 3,
    strength: 1,
    looks: 5,
    image: "images/scandalousgnome.jpg",
  },
  {
    name: "Homeless Gnome",
    rizz: 0,
    magic: 0,
    strength: 3,
    looks: 3,
    image: "images/homelessgnome.jpg",
  },
  {
    name: "Saggin Gnome",
    rizz: 9,
    magic: 2,
    strength: 10,
    looks: 7,
    image: "images/saggingnome.jpg",
  },
  {
    name: "Rocker Gnome",
    rizz: 10,
    magic: 9,
    strength: 5,
    looks: 10,
    image: "images/rockergnome.jpg",
  },
  {
    name: "Zombie Gnome",
    rizz: 0,
    magic: 0,
    strength: 10,
    looks: 0,
    image: "images/zombiegnome.jpg",
  },
  {
    name: "Magic Gnome",
    rizz: 10,
    magic: 10,
    strength: 10,
    looks: 10,
    image: "images/magicgnome.jpg",
  },
  {
    name: "Terraira Gnome",
    rizz: 9,
    magic: 6,
    strength: 5,
    looks: 8,
    image: "images/terrairagnome.jpg",
  },
  {
    name: "Ginger Crochet Gnome",
    rizz: 7,
    magic: 9,
    strength: 6,
    looks: 7,
    image: "images/gingercrochet.jpg",
  },
  {
    name: "Stupid Baby Gnome",
    rizz: 0,
    magic: 0,
    strength: 0,
    looks: 0,
    image: "images/stupidbaby.jpg",
  },
  {
    name: "Fortnite Gnome",
    rizz: 8,
    magic: 9,
    strength: 5,
    looks: 6,
    image: "images/fortnitegnome.jfif",
  },
  {
    name: "Enlightened One",
    rizz: 10000,
    magic: 10000,
    strength: 10000,
    looks: 10000,
    image: "images/enlightenedone.jpg",
  },
  {
    name: "Patriot Gnome",
    rizz: 9,
    magic: 8,
    strength: 7,
    looks: 5,
    image: "images/americangnome.jpg",
  },
  {
    name: "Christmas Gnome",
    rizz: 7,
    magic: 5,
    strength: 6,
    looks: 9,
    image: "images/christmasgnome.jpg",
  },
  {
    name: "Powerlifter Gnome",
    rizz: 5,
    magic: 7,
    strength: 9,
    looks: 8,
    image: "images/swolgnome.jpg",
  },
  {
    name: "Bee Gnome",
    rizz: 8,
    magic: 5,
    strength: 6,
    looks: 7,
    image: "images/beegnome.webp",
  },
  {
    name: "Character 17",
    rizz: 6,
    magic: 9,
    strength: 8,
    looks: 5,
    image: "",
  },
  {
    name: "Character 18",
    rizz: 9,
    magic: 7,
    strength: 6,
    looks: 8,
    image: "",
  },
  {
    name: "Character 19",
    rizz: 7,
    magic: 6,
    strength: 9,
    looks: 5,
    image: "",
  },
  {
    name: "Character 20",
    rizz: 5,
    magic: 8,
    strength: 7,
    looks: 9,
    image: "",
  },
];

export { gnomes };
